### PR TITLE
Norwegian Localisation

### PR DESCRIPTION
**Pull request by vkbo**
This PR adds Norwegian localisation, and also adds a number of newly discovered missing translation locations.

### CODE REVIEW

**Comment by vkbo** [comment]
I keep finding strings that aren't translated, although not as often as before. I'm adding them to this PR, so after this is merged, you should probably have a quick update of the Portuguese `.ts` file too, @bkmeneguello.

**Comment by bkmeneguello** [comment]
Those missing translations are due some merges I had to do. Some of them I remember have translated 😬

**Comment by vkbo** [comment]
Ok, I'm done and will merge this now. It is a lot of work translating 920 strings!

There seems to be about 20 or so missing in Portuguese now. I recovered a few that I changed in the code. Most are new strings that were missing.

I don't understand Portuguese enough to check, but I made this mistake in Norwegian, so just note that the word "Characters" both refers to the counting of text characters (letters) in the text files and other times to characters (people) in the story. In English this is the same word, but not in Norwegian. Don't know about Portuguese.

**Comment by bkmeneguello** [comment]
FYI, in portuguese there are two words for character too, they are covered
in my translation. I'll try to update the portuguese translation today an
submit a new PR.

**Pull request merged**
