### PR TITLE
style: Rewordng of README

### PR DESCRIPTION
**Pull request by mgrhm**
Introduction rewritten for clarity and conciseness.

I've stopped here before doing more work because I'm not sure it's work you want done.

I don't think that the README is structured in the best way.  It jumps back and forth between information about the software and technical information on how it's made.  That could be correct for the target audience, but I'm of the opinion that information about the software, and how to use it, should come _before_ detailed technical information.

I'd structure is like so:

1. Introduction
1. Key Features with Screenshot
1. Installation and Running
1. Implementation
1. Debugging
1. License

Let me know what you think, and if you want it structured like this – I’m happy to do the restructuring and some rewrites for clarity while doing so.

### CODE REVIEW

**Comment by vkbo** [comment]
Thanks. I've been making a lot of changes to the main README file lately, and it's growing a bit messy from all the iterative edits. I agree it needs restructuring, and I'm happy to take some suggestions here.

I don't think I'll take this PR though, for a couple of reasons.

Firstly, regarding the re-wrap. This entire project uses a 99 character line limit, which is one of the options for Python code (PEP8). I also apply it to text files for consistency. I have strong objections to the punch card legacy of 72 characters (I've worked extensively with Fortran 77 code and I thoroughly hate this norm still being around). As a general rule, I add a line break to the end of each sentence, which makes diffs significantly more meaningful. This is the rule I'm accustomed to from collaborating on academic papers. Following a convention that requires re-wrap whenever words inside a paragraph are changed makes diffs significantly *less* readable in my opinion. For short pieces of text like here, I still think re-wrap is more GitHub-friendly, so I've decided on sticking to a repository-wide rule of 99 characters. Anything shorter becomes clunky with URLs etc.

As for the intro rewrite, I am planning to do that anyway, but some of the changes you've made changes fundamental points I'm trying to make, so I won't keep this as-is either, but I'm happy to take some of your suggestions.

I do appreciate all the suggestions and PRs I've been receiving lately on this otherwise anonymous project. But I am very unlikely to take PRs that change conventions I'm currently using across my projects without first discussing them.

**Comment by vkbo** [comment]
Let me also add that I'm trying to figure out the best way of distributing the key information between the main README, the documentation, and the website. I've ended up repeating a lot of the same information, and also ended up having them diverge, which causes issues and confusion.

In principle, the main repo README could be fairly technical, and link to the instructions in the documentation instead. I've started to move in that direction already, but haven't completed it. I'd be happy for some feedback on this too.

**Comment by mgrhm** [comment]
> In principle, the main repo README could be fairly technical, and link to the instructions in the documentation instead. I've started to move in that direction already, but haven't completed it. I'd be happy for some feedback on this too.

That makes sense.  I hadn't really thought about it like that before, but it makes sense that the README is fairly technical because it's about the repo and working on said repo.  There _is_ a distinction between user documentation and programmer documentation.  The README is the latter.

Speaking of diffs and line breaks, my personal preference is [semantic line breaks](https://rhodesmill.org/brandon/2012/one-sentence-per-line/), which are similar to your newline-after-each-sentence style.  As far as 72 columns goes, I like it mostly because it's a convention, and also because it stops lines being ridiculously long.  It's pretty ugly otherwise.

**Comment by vkbo** [comment]
> Speaking of diffs and line breaks, my personal preference is [semantic line breaks](https://rhodesmill.org/brandon/2012/one-sentence-per-line/), which are similar to your newline-after-each-sentence style. As far as 72 columns goes, I like it mostly because it's a convention, and also because it stops lines being ridiculously long. It's pretty ugly otherwise.

For very long sentences, I tend to add a break at commas too, to avoid ridiculously long lines. But often that also means the sentence is too long and should be broken up anyway.

As for line length, it is good to stay below the character limit of the GitHub diff display anyway, which I think is about 127 characters.

**Pull request closed without merging**
