### PR TITLE
Changes to MacOS build

### PR DESCRIPTION
**Pull request by vkbo**
**Summary:**

This is a continuation of #1276 by @Ryex 

**Related Issue(s):**

**Reviewer's Checklist:**

* [x] The header of all files contain a reference to the repository license
* [x] The overall test coverage is increased or remains the same as before
* [x] All tests are passing
* [x] All flake8 checks are passing and the style guide is followed
* [x] Documentation (as docstrings) is complete and understandable
* [x] Only files that have been actively changed are committed

### CODE REVIEW

**Comment by vkbo** [comment]
@Ryex

There are some issues with the app bundle. For one, it's 176 MB. A lot of that is because there is both a "python3.1" and "python3.10" folder in Resources/lib. That seems wrong to me. Any ideas?

Also, can you test the artifacts?

**Comment by vkbo** [comment]
Ok, tested the app bundle on my macOS VM, and it ran just fine. Couldn't get the DMG one to work though, just got a window with an icon that did nothing. Maybe I'm doing something wrong.

**Comment by vkbo** [comment]
I ran the conda command in an Ubuntu VM, and it does indeed create a "python3.1", but as a symlink to "python3.10" I guess the safest would be to preserve symlinks in the build too.

**Comment by Ryex** [comment]
> I ran the conda command in an Ubuntu VM, and it does indeed create a "python3.1", but as a symlink to "python3.10" I guess the safest would be to preserve symlinks in the build too.

This is correct, I'm not sure *why* it's done this way but it's probably preferable to preserve it.

I'll test the dmg here shortly

**Comment by Ryex** [comment]
> @Ryex
> 
> There are some issues with the app bundle. For one, it's 176 MB. A lot of that is because there is both a "python3.1" and "python3.10" folder in Resources/lib. That seems wrong to me. Any ideas?
> 
> Also, can you test the artifacts?

The size of the app bundle is sadly not something that can be worked around. the bundle contains all the libs (python, qt, enchant, etc) it needs to run with the assumption that it can not pull anything from the system. This is the design of app bundles and why they work (for the most part) universally across mac os versions.

**Comment by vkbo** [comment]
> > I ran the conda command in an Ubuntu VM, and it does indeed create a "python3.1", but as a symlink to "python3.10" I guess the safest would be to preserve symlinks in the build too.
> 
> This is correct, I'm not sure _why_ it's done this way but it's probably preferable to preserve it.

It didn't work, so I've now tried to remove it. As far as I can figure out, it's a backwards compatibility thing for older conda versions. I bet they treated the Python version as a number, where 3.10 becomes 3.1.

> I'll test the dmg here shortly

Great. I noticed that it isn't always built properly though. Same error as mentioned here: https://github.com/create-dmg/create-dmg/issues/74

**Comment by vkbo** [comment]
> The size of the app bundle is sadly not something that can be worked around. the bundle contains all the libs (python, qt, enchant, etc) it needs to run with the assumption that it can not pull anything from the system. This is the design of app bundles and why they work (for the most part) universally across mac os versions.

Oh, it can definitely be worked around. I reduced the size of the windows package quite a lot by deleting components of Qt not needed by novelWriter. It actually only needs core, widgets and svg. I got it down to just over 100 MB, which is good enough for now.

**Comment by Ryex** [comment]
> > The size of the app bundle is sadly not something that can be worked around. the bundle contains all the libs (python, qt, enchant, etc) it needs to run with the assumption that it can not pull anything from the system. This is the design of app bundles and why they work (for the most part) universally across mac os versions.
> 
> Oh, it can definitely be worked around. I reduced the size of the windows package quite a lot by deleting components of Qt not needed by novelWriter. It actually only needs core, widgets and svg. I got it down to just over 100 MB, which is good enough for now.

True enough, there is a reason I was pruning the web-engine after all. so long as your aware of what your pruning and why it can be cut down a bit further.

**Comment by vkbo** [comment]
> True enough, there is a reason I was pruning the web-engine after all. so long as your aware of what your pruning and why it can be cut down a bit further.

All of the QtQuick/QML stuff can be pruned too, so can the database and other bits. But it's a lot of stuff to loop through and remove. I do it here for Windows:

https://github.com/vkbo/novelWriter/blob/8273fcca1e784e6092bf38b8c873d946063c21e5/setup.py#L1291-L1324

I may just make a Qt cleanup function in `setup.py` for it some other time.

**Comment by Ryex** [comment]
Just tested the dmg form the last packaging action on my ventura VM.  91MB, seems to work fine. ^-^

**Comment by vkbo** [comment]
> Just tested the dmg from the last packaging action on my ventura VM. 91MB, seems to work fine. ^-^

Excellent. Then I'll merge this. I'm trying to find a way to properly run the workflow. Unfortunately GitHub doesn't have a `manual` setting like GitLab does.

**Comment by vkbo** [comment]
Hah, I cracked it. I managed to get the `on: workflow_dispatch` to work. I just needed to add a mock workflow to the default branch, and it showed up in my Actions tab. I can then run the workflow on any branch I want.

By the way, my solution to the texlive/qt-linguist issue was to build the assets on a Linux runner first, and then download those into the MacOS runner for making the packages.

**Comment by Ryex** [comment]
Smart!

Glad I was able to help out with this. I'm sure there are at least some users looking forward to a proper bundle release.

Now you just need flatpak and you'll be effectively everywhere  (i've been personally useing my flatpak build both on my desktop and to get it on my older laptop)

**Pull request merged**
